### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by muhammadumer26** [Depart-de-Sentier/visualization-contest-brightcon-2022#1]
@cmutel @tngTUDOR
Dear Mr. Chris
Hope you are having a great time,
Kindly if you could tell, do we have to use the code that you have provided in the Visualization fixtures creation.ipynb and make the visualization for this, or can we create a custom code as well and use it?
Much Obliged
Muhammad Umer

**Comment by tngTUDOR** [comment]
Hi there,

You can use your own custom code ;)

**Comment by muhammadumer26** [comment]
Thanks for the response :)
